### PR TITLE
Update remaining generated files to run in python

### PR DESCRIPTION
**Pull request by davidbraden**

### CODE REVIEW

**Comment by harrybraden** [comment]
Dear David,

I have added 8 more files. Could you do your magic and group them into two 2x2 matrices in evaluated form, i.e. they will be numerical and used in the energy density program. I think it is obvious  ddphi2 = [ [ ddphi211 , ddphi212] , [ ddphi221 , ddphi222 ]]
etc.

Something has gone wrong with my ddph1, the remaining 4 files�I am having to rerun.

I think I have put these on github successfully.

Love Dad

**Comment by harrybraden** [comment]
Dear David,

can you take me through the stages of getting your updates, and adding my 4 new files. With  

~/Documents/MonopoleMovie/python_expressions:$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

```
new file:   ddphi211.py
new file:   ddphi212.py
new file:   ddphi221.py
new file:   ddphi222.py
new file:   ddphi311.py
new file:   ddphi312.py
new file:   ddphi321.py
new file:   ddphi322.py
```

Untracked files:
  (use "git add <file>..." to include in what will be committed)

```
../.DS_Store
../.idea/
../MonopoleMovie.iml
../playground.py
ddphi111.py
ddphi112.py
ddphi121.py
ddphi122.py
```

The top ones are in green and untracked in red.  The final 4 files need the same magic, then we are ready to roll.  A question: is there a way to read in all the files from the subdirectory
python_expressions without naming each one?

Love, Dad

**Comment by davidbraden** [comment]
git add ddphi111.py
git add ddphi112.py
git add ddphi121.py
git add ddphi122.py

git commit -m "Adding matrix elements"

git pull
git push

I don't know about import all files without naming.

David

**Comment by harrybraden** [comment]
Dear David,

/Documents/MonopoleMovie/python_expressions:$ git add ddphi111.py
~/Documents/MonopoleMovie/python_expressions:$ git add ddphi112.py
~/Documents/MonopoleMovie/python_expressions:$ git add ddphi121.py
~/Documents/MonopoleMovie/python_expressions:$ git add ddphi122.py
~/Documents/MonopoleMovie/python_expressions:$ git commit -m "Adding matrix elements"
[master 6d14c99] Adding matrix elements
 12 files changed, 12 insertions(+)
 create mode 100755 python_expressions/ddphi111.py
 create mode 100755 python_expressions/ddphi112.py
 create mode 100755 python_expressions/ddphi121.py
 create mode 100755 python_expressions/ddphi122.py
 create mode 100755 python_expressions/ddphi211.py
 create mode 100755 python_expressions/ddphi212.py
 create mode 100755 python_expressions/ddphi221.py
 create mode 100755 python_expressions/ddphi222.py
 create mode 100755 python_expressions/ddphi311.py
 create mode 100755 python_expressions/ddphi312.py
 create mode 100755 python_expressions/ddphi321.py
 create mode 100755 python_expressions/ddphi322.py

This has invoked 12 files, not the most recent 4? Has it overwritten what you did?

D.

**Comment by davidbraden** [comment]
I don't think you had committed any of the 12 files. I've not made changes
to any of those files yet...

**Comment by harrybraden** [comment]
If you haven�t made any changes, how do I make sure the latest variants are available for you? I have edited away some extra lines, so there is just the code, on the variants I have. What git command will see the latest are out there?

**Comment by davidbraden** [comment]
if you go to
https://github.com/harrybraden/monopole/tree/master/python_expressions you
can see what you have made available

**Comment by harrybraden** [comment]
ED1:= Trace( (DDH[1].IGNUM -2_DH[1].IGNUM.DG[1].IGNUM 
         +HNUM.( 2_IGNUM.DG[1].IGNUM.DG[1].IGNUM - IGNUM.DDG[1].IGNUM )).HNUM.IGNUM)
         +Trace( (DH[1].IGNUM -  HNUM.IGNUM.DG[1].IGNUM)^2 );

ED2:= Trace( (DDH[2].IGNUM -2_DH[2].IGNUM.DG[2].IGNUM 
          +HNUM.( 2_IGNUM.DG[2].IGNUM.DG[2].IGNUM - IGNUM.DDG[2].IGNUM )).HNUM.IGNUM)
          +Trace( (DH[2].IGNUM -  HNUM.IGNUM.DG[2].IGNUM)^2 );

ED3:= Trace( (DDH[3].IGNUM -2_DH[3].IGNUM.DG[3].IGNUM 
           +HNUM.( 2_IGNUM.DG[3].IGNUM.DG[3].IGNUM - IGNUM.DDG[3].IGNUM )).HNUM.IGNUM)
         +Trace( (DH[3].IGNUM -  HNUM.IGNUM.DG[3].IGNUM)^2 );

 -Re(ED1+ED2+ED3);

where IGNUM is Inverse of GRAM

H stands for Phi   so HNUM is Phi evaluated, DH is the derivative etc

**Comment by harrybraden** [comment]
time0:=time():
DTEST([0.7,0,0,0.9]);
time()-time0;
                   HFloat(0.6367435093726227)
                             3.062

**Pull request merged**
