### PR TITLE
Visualisation

### PR DESCRIPTION
**Pull request by peterbraden**

### CODE REVIEW

**Comment by harrybraden** [comment]
Dear Peter,

is there a way I can recall my old ‘main.py’ which had a number of things I would like. It doesn’t have to be called main.py. Can you rename it old_main or something and
send or tell me how to get it. I guess I should read the git manual: is there a good account somewhere?

Thanks,
Dad

**Comment by peterbraden** [comment]
If you look at the history of that file (https://github.com/harrybraden/monopole/commits/master/main.py) - which you can get by clicking the history link on the file you're interested in, then you get a list of all of the changes to that file. You can click on the one you're interested in and see what has changed (additions are in green, deletions in red).

**Comment by peterbraden** [comment]
Looks like what you had in that file before was:

``` python
t0 = time.time()
A  = energy_density(.8, 1.5, 0.9, 0.3)
t1 = time.time()

print A
print str(t1-t0)

# t2 = time.time()
# B  = higgs_squared(.8, 1.5, 0.0, 0.0)
# t3 = time.time()
#
# print B
# print str(t3-t2)


# t0 = time.time()
# print higgs_squared(0.8, 2.01, 0, 0)
# t1 = time.time()
# print str(t1-t0)

# print "%.8f"%  higgs_squared(0.8 , 1 , 0.5 , 0.04)



# fo = open(os.path.expanduser("~/Desktop/numerical monopoles/hwb_testhiggs_2"), 'w' )
# for i in range(0, 400, 1):
#     fo.write("%4.2f %15.9f\n"% ( (float(2*i) +2)/100, higgs_squared(0.8 ,  0.0, (float(2*i) +2)/100, 0.00 )    ))
# fo.close() 
```

**Comment by harrybraden** [comment]
Dear Peter,

Visualisation is your file. I have made no  changes to it.

How can I set a global variable in my ‘main’ or ‘file’ and pass it through to the programmes I collect from other files (e.g. my energy_density one)? At the moment I have
set maxint in energy_density.

Love dad

**Pull request merged**
