### PR TITLE
More work

### PR DESCRIPTION
**Pull request by davidbraden**

### CODE REVIEW

**Comment by harrybraden** [comment]
Dear David,

can you tell me the git commands I should do to update please. Will it be 

git merge

? or something else. What have you done…it looks a lot.

Love Dad.

**Comment by davidbraden** [comment]
Git pull after merging the changes in github.

I've made all the files runnable and added the expression from your email
at the bottom of main. It doesn't give the right number so there is
something wrong somewhere. It's also takes several seconds so I'm not sure
will be quicker than maple.

David

**Comment by harrybraden** [comment]
Can you give me the commands from my terminal in the correct order please?

> Git pull after merging the changes in github.

Not sure what you are asking me to type.

D.

**Comment by davidbraden** [comment]
You have to merge my changes in github through the ui

Then git pull

**Comment by harrybraden** [comment]
> You have to merge my changes in github through the ui

I dont understand this. This is the web interface you previously sent a link to?

> Then git pull

**Comment by davidbraden** [comment]
Github.com

**Comment by harrybraden** [comment]
David, I am on harrybraden/monopole and I am asking what you are asking me to do to merge. 

 harrybraden committed on GitHub Merge pull request #2 from davidbraden/master …
python_expressions  Merge pull request #2 from davidbraden/master   4 days ago
.gitignore  Initial commit  3 months ago
laplace.py  Add energy density in volume    13 days ago
main.py main hopefully added    11 days ago
matrices.py changes speaking to david   12 days ago
Add a README

**Comment by davidbraden** [comment]
https://github.com/harrybraden/monopole/pull/3

**Comment by harrybraden** [comment]
Adding Davids changes

**Comment by harrybraden** [comment]
Presume I have merged. git pull gives the following abort

Updating 6dfabe2..7096f28
error: Your local changes to the following files would be overwritten by merge:
    main.py
    python_expressions/ddphi111.py
    python_expressions/ddphi112.py
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by harrybraden** [comment]
I have moved the 3 files mentioned and git pull has worked. Will play with what you have given.

**Comment by harrybraden** [comment]
David,

I am not finding matmul in numpy and getting the error 
ImportError: cannot import name matmul
Google not helping

Dad

**Pull request merged**
